#!/usr/bin/env ruby

require 'xcodeproj'


HEADER_DIR = "include"
OBJC_HEADER_DIR = HEADER_DIR + "/objc"
LLVMLINK="/Users/fchiba/emsdk/clang/e1.27.0_64bit/llvm-link"

#task "default" => ["header", "obj"]
task "default" => ["closure.bc"]

project = Xcodeproj::Project.open("Blocks.xcodeproj")
p project.targets
target = project.targets.select{|t| t.name == "Blocks"}.first

objc_headers = nil
target.build_phases.each{ |phase|
	if phase.isa == "PBXHeadersBuildPhase"
		files = phase.files_references
		files.each{ |file|
#			p file
		}
		objc_headers = files.map{|f| f.path}
	elsif phase.isa == "PBXSourcesBuildPhase"
		files = phase.files_references
		files.each{ |file|
			p file
		}
		files = files.map{|f| f.path.gsub(/\.c+$/, ".o")}
		task "closure.bc" => files do |t|
			sh "#{LLVMLINK} -o closure.bc #{t.prerequisites.join(" ")}"
		end
	end
}

other_headers = FileList["*.h"]

directory HEADER_DIR
directory OBJC_HEADER_DIR

task "header" => ["objc_headers", "other_headers"]

task "objc_headers" => objc_headers do |t|
	cp t.prerequisites, OBJC_HEADER_DIR
end

task "other_headers" => other_headers do |t|
	cp t.prerequisites, HEADER_DIR
end


CC = "emcc"
INCLUDE = "-I./include -I./include/objc -I./runtime -I../../apple/objc4 -I./"
COPTS = "-v -fblocks"
CFLAGS="#{INCLUDE} #{COPTS}"

rule ".o" => ".c" do |t|
	sh "#{CC} #{CFLAGS} -o #{t.name} -c #{t.source}"
end

rule ".o" => ".m" do |t|
	sh "#{CC} #{CFLAGS} -o #{t.name} -c #{t.source}"
end

rule ".o" => ".mm" do |t|
	sh "#{CC} #{CFLAGS} -o #{t.name} -c #{t.source}"
end

rule ".o" => ".s" do |t|
	sh "#{CC} #{CFLAGS} -o #{t.name} -c #{t.source}"
end
